### ISSUE TITLE
The message type ‘aruco_interfaces/msg/ArucoMarkers’ is invalid

### ISSUE THREAD

**Issue by svetlana-aristova** [AIRLab-POLIMI/ros2-aruco-pose-estimation#2]
Hello

Please tell me why when I try to listen to the topic /aruco/markers
I see the message - The message type ‘aruco_interfaces/msg/ArucoMarkers’ is invalid ?

**Comment by aiba-gento** [comment]
Hello
I'm a beginner in English so please be patient.

I'm guessing the first time you saw that error message was when using "ros2 topic echo /aruco/markers".
If so, I think you need to run the following command:

cd ros2_ws
source install/setup.bash
ros2 topic echo /aruco/markers

The above commands are:
1. Go to workspace. (The workspace where you built the package.)
2. Reflect the overlay configuration file.
3. Listen to the topic.
These are general commands, so change them to fit your environment.

I think that the message - "The message type ‘aruco_interfaces/msg/ArucoMarkers’ is invalid ? " occurs because the overlay configuration file is not reflected.

**Comment by svetlana-aristova** [comment]
Thank you very much for your explanation. The problem was that I did it without going into the package. Now everything works correctly. What should I do to make this topic available to me in rviz and not only inside the package? Maybe I have something else not configured. I am a newbie in this business.

![ 12 35 49](https://github.com/user-attachments/assets/fd96826f-b0f6-4a41-b4b5-0e36d1dcfef7)

**Comment by aiba-gento** [comment]
Although it is difficult to display, aruco_node outputs /aruco/image . The image in /aruco/image contains the maker ID.
![image](https://github.com/user-attachments/assets/65d8d074-e5cb-4219-8f15-9cb02718130d)

**Comment by svetlana-aristova** [comment]
Only on /aruco/image can I see the maker ID? I would like to see it on the map, as shown in the image below. Is it possible to customize this display? So that the maker ID is displayed on the map.



![rviz_example](https://github.com/user-attachments/assets/82ad9162-8aec-420e-aebe-2b459575d82e)

**Comment by aiba-gento** [comment]
I think that image is a TF, not a PoseArray.
TF has a "Show Names" option.
![image](https://github.com/user-attachments/assets/85866cf0-748c-43a5-ba32-73d7fbaa5810)

![Screenshot from 2024-07-31 22-20-53](https://github.com/user-attachments/assets/9ded5f83-2de0-4a48-a651-5802fbbaa151)

To display TF, add the following code to "ros2-aruco-pose-estimation/aruco_pose_estimation/scripts/aruco_node.py":

```c++
from tf2_ros import TransformStamped # line 57
from tf2_ros import TransformBroadcaster

        self.tf_pub = self.create_publisher(TransformStamped, "/tf_aruco", 10) # line : 117
        self.tf_broadcaster = TransformBroadcaster(self)

            for i in range(len(markers.marker_ids)): # line : 193
                tf = TransformStamped()
                tf.header.stamp = img_msg.header.stamp
                tf.header.frame_id = "camera_link"
                tf.child_frame_id = f"aruco_{markers.marker_ids[i]}"
                tf.transform.translation.x = pose_array.poses[i].position.x
                tf.transform.translation.y = pose_array.poses[i].position.y
                tf.transform.translation.z = pose_array.poses[i].position.z
                tf.transform.rotation = pose_array.poses[i].orientation
                odometry = tf.transform.translation
                quaternion = tf.transform.rotation
                self.tf_pub.publish(tf)
                self.tf_broadcaster.sendTransform(tf)
```
                
![image](https://github.com/user-attachments/assets/382a6edd-04ed-4736-94ed-aa6d45e2d80b)
![image](https://github.com/user-attachments/assets/f15fb335-9a96-431f-84c2-91b62679ea51)
![image](https://github.com/user-attachments/assets/c26bf530-8bf9-4e6b-bb99-25e43f2be5c1)

I haven't checked it so I don't know if the coordinates are correct, but it worked with the above addition.

**Comment by svetlana-aristova** [comment]
Thanks a lot for the detailed answer and help.

**Comment by SimonGiampy** [comment]
Thank you guys for your quick answers and explanations
